import { PERMISSIONS, type Permission } from './constants';

export type Role = 'SUPER_ADMIN' | 'ADMIN' | 'THERAPIST' | 'STAFF' | 'USER';

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SUPER_ADMIN: [
    PERMISSIONS.APPOINTMENT_LIST,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.CALENDAR_EVENT_READ,
    PERMISSIONS.CALENDAR_EVENT_MANAGE,
    PERMISSIONS.INTAKE_READ,
    PERMISSIONS.INTAKE_ARCHIVE,
    PERMISSIONS.PATIENT_LIST,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_ARCHIVE,
    // Administration only. Clinical permissions require an explicit future grant.
    // Administration
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_LIST,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_SUSPEND,
    PERMISSIONS.USER_REACTIVATE,
    PERMISSIONS.ROLE_ASSIGN,
    PERMISSIONS.PERMISSION_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.SETTINGS_MANAGE,
  ],
  ADMIN: [
    PERMISSIONS.CALENDAR_EVENT_READ,
    PERMISSIONS.CALENDAR_EVENT_MANAGE,
    PERMISSIONS.PROGRESS_READ,
    PERMISSIONS.APPOINTMENT_LIST,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.APPOINTMENT_CANCEL,
    PERMISSIONS.APPOINTMENT_RESCHEDULE,
    PERMISSIONS.APPOINTMENT_COMPLETE,
    // Patient domain
    PERMISSIONS.PATIENT_LIST,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE_DEMOGRAPHICS,
    PERMISSIONS.PATIENT_ASSIGN,
    // Intake
    PERMISSIONS.INTAKE_READ,
    PERMISSIONS.INTAKE_REVIEW,
    PERMISSIONS.INTAKE_REQUEST_REVISION,
    PERMISSIONS.INTAKE_ACCEPT,
    // Assessment
    PERMISSIONS.ASSESSMENT_READ,
    PERMISSIONS.ASSESSMENT_CREATE,
    PERMISSIONS.ASSESSMENT_UPDATE_DRAFT,
    PERMISSIONS.ASSESSMENT_FINALIZE,
    PERMISSIONS.ASSESSMENT_AMEND,
    // Treatment plan
    PERMISSIONS.TREATMENT_PLAN_READ,
    PERMISSIONS.TREATMENT_PLAN_CREATE,
    PERMISSIONS.TREATMENT_PLAN_UPDATE_DRAFT,
    PERMISSIONS.TREATMENT_PLAN_FINALIZE,
    PERMISSIONS.TREATMENT_PLAN_AMEND,
    // Sessions
    PERMISSIONS.SESSION_READ,
    PERMISSIONS.SESSION_CREATE,
    PERMISSIONS.SESSION_UPDATE_DRAFT,
    PERMISSIONS.SESSION_FINALIZE,
    PERMISSIONS.SESSION_AMEND,
    // Documents
    PERMISSIONS.DOCUMENT_LIST,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_DOWNLOAD,
    // Administration
    PERMISSIONS.USER_LIST,
    PERMISSIONS.USER_READ,
    PERMISSIONS.AUDIT_READ,
  ],
  THERAPIST: [
    PERMISSIONS.CALENDAR_EVENT_READ,
    PERMISSIONS.PROGRESS_READ,
    PERMISSIONS.APPOINTMENT_LIST,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.APPOINTMENT_CANCEL,
    PERMISSIONS.APPOINTMENT_RESCHEDULE,
    PERMISSIONS.APPOINTMENT_COMPLETE,
    // Patient domain (scoped to assigned patients)
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_LIST,
    // Intake (scoped)
    PERMISSIONS.INTAKE_READ,
    PERMISSIONS.INTAKE_REVIEW,
    PERMISSIONS.INTAKE_REQUEST_REVISION,
    PERMISSIONS.INTAKE_ACCEPT,
    // Assessment (scoped)
    PERMISSIONS.ASSESSMENT_READ,
    PERMISSIONS.ASSESSMENT_CREATE,
    PERMISSIONS.ASSESSMENT_UPDATE_DRAFT,
    PERMISSIONS.ASSESSMENT_FINALIZE,
    PERMISSIONS.ASSESSMENT_AMEND,
    // Treatment plan (scoped)
    PERMISSIONS.TREATMENT_PLAN_READ,
    PERMISSIONS.TREATMENT_PLAN_CREATE,
    PERMISSIONS.TREATMENT_PLAN_UPDATE_DRAFT,
    PERMISSIONS.TREATMENT_PLAN_FINALIZE,
    PERMISSIONS.TREATMENT_PLAN_AMEND,
    // Sessions (scoped)
    PERMISSIONS.SESSION_READ,
    PERMISSIONS.SESSION_CREATE,
    PERMISSIONS.SESSION_UPDATE_DRAFT,
    PERMISSIONS.SESSION_FINALIZE,
    PERMISSIONS.SESSION_AMEND,
    // Documents (scoped)
    PERMISSIONS.DOCUMENT_LIST,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_DOWNLOAD,
  ],
  STAFF: [
    PERMISSIONS.CALENDAR_EVENT_READ,
    PERMISSIONS.APPOINTMENT_LIST,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.APPOINTMENT_CANCEL,
    PERMISSIONS.APPOINTMENT_RESCHEDULE,
    PERMISSIONS.APPOINTMENT_COMPLETE,
    // Patient domain (minimum)
    PERMISSIONS.PATIENT_LIST,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE_DEMOGRAPHICS,
    // Intake (minimum)
    PERMISSIONS.INTAKE_READ,
    // Documents (limited)
    PERMISSIONS.DOCUMENT_LIST,
    PERMISSIONS.DOCUMENT_READ,
    // Administration (limited)
    PERMISSIONS.USER_LIST,
    PERMISSIONS.USER_READ,
  ],
  USER: [
    PERMISSIONS.CALENDAR_EVENT_READ,
    PERMISSIONS.PROGRESS_READ_OWN,
    PERMISSIONS.APPOINTMENT_LIST,
    PERMISSIONS.APPOINTMENT_READ,
    // Patient domain (own only)
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_UPDATE_DEMOGRAPHICS,
    // Intake (own)
    PERMISSIONS.INTAKE_CREATE_OWN,
    PERMISSIONS.INTAKE_UPDATE_OWN_DRAFT,
    PERMISSIONS.INTAKE_READ,
    // Assessment (visible own)
    PERMISSIONS.ASSESSMENT_READ,
    // Treatment plan (visible own)
    PERMISSIONS.TREATMENT_PLAN_READ,
    // Sessions (visible own)
    PERMISSIONS.SESSION_READ,
  ],
};
